server.port=8081

spring.application.name=USER-SERVICE

user.service.message=User Service is running from Config Server

spring.datasource.url=jdbc:mysql://localhost:3306/microservices_db
spring.datasource.username=root
spring.datasource.password={cipher}7e0c796c006cac42164e36212c02156b09a467ccbe6851a1e817a435b2c9fd3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
